stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-baff-buero:${CICD_EXECUTION_SEQUENCE}
  when:
    branch: {}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./build/deployment.yaml
  when:
    branch: {}
branch:
  include:
  - master
notification: {}
